apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      - name: personal-website
        image: public.ecr.aws/j0l2f7n2/personal-website:developement
        ports:
        - containerPort: 3000