apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: personal-website
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      - name: personal-website
        image: 954447000905.dkr.ecr.us-east-1.amazonaws.com/personal-website:developement
        ports:
        - containerPort: 3000